server:
  port: 8080
openapi:
  devUrl: http://localhost:8080
  prodUrl: http://localhost:9090

spring:
  javaVersion: 17
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: MiladImdb
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
  api-docs:
    enabled: true

application:
  version: 1.0
  security:
    jwt:
      secret-key: 743777217A25432A462D4A614E635266556A586E3272357538782F413F442847
      expiration: 8640000000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

debug: true